name: Curl | Bash Test
on:
  push:
    paths:
      - install.sh.in
      - .github/workflows/ci.yml
  workflow_dispatch:
  pull_request:
    paths:
      - install.sh.in
      - .github/workflows/ci.yml
  schedule:
    - cron: "0 0 * * 0"   # weekly
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: sudo apt install -y shellcheck
      - run: shellcheck -S error install.sh.in

  curl-bash:
    needs: shellcheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - "ubuntu:latest"
          - "ubuntu:24.10"
          - "ubuntu:24.04"
          - "ubuntu:22.04"
          - "ubuntu:20.04"
          - "debian:latest"
          - "debian:12"
          - "debian:11"
          - "debian:10"
          - "linuxmintd/mint22-amd64:latest"
          - "kalilinux/kali-rolling:latest"
          - "redhat/ubi9:latest"
          - "rockylinux/rockylinux:latest"
          - "fedora:latest"
          - "fedora:rawhide"

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: apt
        run: apt-get -y update && apt-get -y install curl gnupg2 gnupg gpg || true
      - name: install ${{ matrix.container }}
        run: bash install.sh.in
